Repository nexfoundation/vanilla, pull requests merged in 2021-01, with the labels that each got.

#6 update #2: customize the title bar
  addons/themes/theme-nexfoundation/assets/brand.png
  addons/themes/theme-nexfoundation/assets/variables.neon
  addons/themes/theme-nexfoundation/src/scss/custom.scss
  addons/themes/theme-nexfoundation/src/scss/override/banner.scss
  addons/themes/theme-nexfoundation/src/scss/override/titleBar.scss
Labels: kind/ui

#26 feature: expose user name and avatar
  applications/vanilla/models/class.discussionmodel.php
Labels: kind/ui

#7 feature: Add Search API back
  addons/themes/theme-nexfoundation/src/scss/custom.scss
  applications/dashboard/controllers/api/SearchApiController.php
  applications/dashboard/models/class.searchmodel.php
  applications/vanilla/models/class.vanillasearchmodel.php
  applications/vanilla/settings/class.hooks.php
  library/src/scripts/contexts/SearchContext.tsx
  library/src/scripts/search/SearchPage.tsx
Labels: kind/feature

#42 fix: linter errors
  addons/themes/theme-nexfoundation/src/scripts/entries/forum.tsx
  src/scripts/entries/forum.tsx
  src/scss/components/_articleList.scss
  src/scss/custom.scss
Labels: kind/bug
